# Generated by Django 2.1.1 on 2018-12-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Interests',
        ),
    ]
